# Generated by Django 3.2.8 on 2021-10-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password2',
        ),
    ]
